plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\shen\\website\\1hugo\\public"
publishOrigin = "config"
commandOrigin = "config"
command = "hugo --minify"

[build.environment]
HUGO_VERSION = "0.149.0"
HUGO_ENV = "production"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]